### ISSUE TITLE
Not working after installing via your instructions

### ISSUE THREAD

**Issue by wavesailor** [droope/droopescan#26] opened 2018-03-29 09:59 UTC
Hi,
I installed as per you instructions on Ubuntu 16.04.4 LTS:
`sudo apt-get install python-pip`
`pip install droopescan`

It installed fine except for a warning:
`You are using pip version 8.1.1, however version 9.0.3 is available.`
`You should consider upgrading via the 'pip install --upgrade pip' command.`

I then run the command as per your instructions but get the following error:
`myuser@myServer:~$ droopescan scan -u google.com`
`droopescan: command not found`

Any ideas how to get it working?
Thks

**Comment by droope** [comment] 2018-04-20 06:13
Hmm. What version of Debian are you using? can you run the following commands and paste the output here?

```
ls -la /usr/local/bin/droopescan
file /usr/local/bin/droopescan
echo $PATH
cat /etc/debian_version
```

**Comment by wavesailor** [comment] 2018-04-20 10:56
Seems it's not installed where @droope thinks it should be.

```
ls -la /usr/local/bin/droopescan
ls: cannot access '/usr/local/bin/droopescan': No such file or directory
```

```
file /usr/local/bin/droopescan
/usr/local/bin/droopescan: cannot open `/usr/local/bin/droopescan' (No such file or directory)
```

```
sudo locate droopescan
/home/wavesailor/.local/bin/droopescan
.....
```

```
file /home/wavesailor/.local/bin/droopescan
/home/wavesailor/.local/bin/droopescan: Python script, ASCII text executable
```

```
echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/wavesailor/.composer/vendor/bin
```

```
cat /etc/debian_version
stretch/sid
```

**Comment by droope** [comment] 2018-04-20 22:04
I am not 100% sure at this stage how droopescan ended there. It seems that this is a new systemd feature. https://unix.stackexchange.com/questions/316765/which-distributions-have-home-local-bin-in-path

In the meantime adding `/home/wavesailor/.local/bin` to your $PATH will help you, and make droopescan executable.

Add the following to your `~/.bashrc` file:

```
PATH="$PATH:$HOME/.local/bin/"
```

and then run 

```
chmod +x $HOME/.local/bin/droopescan
```

**Comment by wavesailor** [comment] 2018-05-03 12:06
After following your directions above, I got it to work. 
Thanks.

**Comment by droope** [comment] 2018-05-28 22:33
Closing the issue as there is a workaround in place and debian testing is not my biggest priority at the moment. If the issue is present on the stable version of debian please reopen and I'll patch setup.py to account for the new binary location.

**Closed by droope** 2018-05-28 22:33 UTC
