### ISSUE TITLE
timeout issue

### ISSUE THREAD

**Issue by 3xp10it** [droope/droopescan#14] opened 2017-01-21 11:26 UTC
Every time I run:
 droopescan scan drupal -u http://www.drupal.fr -t 8

I will get a timeout error like below,is there something?

modules [============================================       ] 627/700 (89%)
Traceback (most recent call last):
    File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 594, in
    urlopen
    chunked=chunked)
    File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 391, in
    _make_request
    six.raise_from(e, None)
    File "<string>", line 2, in raise_from
    File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line
    387, in _make_request
    httplib_response = conn.getresponse()
    File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
    File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
    File "/usr/lib/python3.5/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
            http.client.RemoteDisconnected: Remote end closed connection without
            response

            During handling of the above exception, another exception occurred:

            Traceback (most recent call last):
            File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py",
            line 423, in send
            timeout=timeout
            File
            "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py",
            line 643, in urlopen
            _stacktrace=sys.exc_info()[2])
            File
            "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/util/retry.py",
    line 334, in increment
            raise six.reraise(type(error), error, _stacktrace)
            File
            "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/packages/six.py",
    line 685, in reraise
            raise value.with_traceback(tb)
            File
            "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py",
            line 594, in urlopen
            chunked=chunked)
            File
            "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py",
    line 391, in _make_request
            six.raise_from(e, None)
            File "<string>", line 2, in
            raise_from
            File
            "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py",
            line 387, in _make_request
    httplib_response =
            conn.getresponse()
            File
            "/usr/lib/python3.5/http/client.py",
    line 1197, in getresponse
            response.begin()
            File
            "/usr/lib/python3.5/http/client.py",
            line 297, in begin
            version, status,
    reason =
            self._read_status()
            File
            "/usr/lib/python3.5/http/client.py",
            line 266, in
            _read_status
            raise
            RemoteDisconnected("Remote
                    end closed
                    connection
                    without"
                    requests.packages.urllib3.exceptions.ProtocolError:
                    ('Connection
                     aborted.',
                     RemoteDisconnected('Remote
                         end closed
                         connection
                         without
                         response',))

                    During
                    handling of
                    the above
                    exception,
                    another
                    exception
                    occurred:

            Traceback
            (most
             recent call
             last):
                File
                "/usr/local/bin/droopescan",
                line 6,
                in
                <module>
                exec(compile(open(__file__).read(),
                            __file__,
                            'exec'))
                File
                "/root/droopescan/droopescan",
                line
                5,
                in
    <module>
            droopescan.main()
                File
                "/root/droopescan/dscan/droopescan.py",
                line
                55,
                in
    main
        ds.run()
                File
                "/usr/local/lib/python3.5/dist-packages/cement/core/foundation.py",
                line
                764,
                in
    run
       self.controller._dispatch()
                File
                "/usr/local/lib/python3.5/dist-packages/cement/core/controller.py",
                line
                466,
                in
                _dispatch
    return
          func()
                File
                "/usr/local/lib/python3.5/dist-packages/cement/core/controller.py",
                line
                472,
                in
                _dispatch
    return
          func()
                File
                "/root/droopescan/dscan/plugins/drupal.py",
                line
                40,
                in
    drupal
          self.plugin_init()
                File
                "/root/droopescan/dscan/plugins/internal/base_plugin_internal.py",
                line
                288,
                in
    plugin_init
               self.process_url(opts,
                       functionality,
                       enabled_functionality,
                       hide_progressbar)
                File
                "/root/droopescan/dscan/plugins/internal/base_plugin_internal.py",
                line
                308,
                in
                process_url
                hide_progressbar=hide_progressbar)
                File
                "/root/droopescan/dscan/plugins/internal/base_plugin_internal.py",
                line
                429,
                in
                url_scan
                finds,
                is_empty
                =
                enum['func'](**kwargs)
                File
                "/root/droopescan/dscan/plugins/internal/base_plugin_internal.py",
                line
                702,
                in
                enumerate_themes
                hide_progressbar,
                imu,
                headers)
                File
                "/root/droopescan/dscan/plugins/internal/base_plugin_internal.py",
                line
                660,
                in
                enumerate
                r
                =
                future_array['future'].result()
                File
                "/usr/lib/python3.5/concurrent/futures/_base.py",
                line
                398,
                in
                result
    return
          self.__get_result()
                File
                "/usr/lib/python3.5/concurrent/futures/_base.py",
                line
                357,
                in
                __get_result
                raise
                self._exception
                File
                "/usr/lib/python3.5/concurrent/futures/thread.py",
                line
                55,
                in
                run
                result
    =
     self.fn(*self.args,
             **self.kwargs)
                File
                "/usr/local/lib/python3.5/dist-packages/requests/sessions.py",
                line
                523,
                in
                head
                return
                self.request('HEAD',
                        url,
                        **kwargs)
                File
                "/usr/local/lib/python3.5/dist-packages/requests/sessions.py",
                line
                488,
                in
                request
                resp
    =
     self.send(prep,
             **send_kwargs)
                File
                "/usr/local/lib/python3.5/dist-packages/requests/sessions.py",
                line
                609,
                in
                send
                r
    =
     adapter.send(request,
             **kwargs)
                File
                "/usr/local/lib/python3.5/dist-packages/requests/adapters.py",
                line
                473,
                in
                send
    raise
         ConnectionError(err,
                 request=request)
                requests.exceptions.ConnectionError:
                ('Connection
                 aborted.',
                 RemoteDisconnected('Remote
                     end
                     closed
                     connection
                     without
                     response',))

**Comment by droope** [comment] 2017-01-22 22:55
你好 @3xp10it 

I can't reproduce that issue with that site. I think it may be due to the connection being unreliable between you and the target site. It is related to #10 in the sense that droopescan could raise that as a warning instead of a fatal exception, although that would make scans less reliable.

**Comment by droope** [comment] 2017-03-17 00:43
hi @3xp10it, I'll close this issue pending more information, pls let me know if you have any more issues.

**Closed by droope** 2017-03-17 00:43 UTC

**Comment by 3xp10it** [comment] 2017-03-17 04:09
no,thx.
